name: Docker Automation
on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login, build
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started1:latest .
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/getting-started1
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Compose up
        run: |
          sudo docker compose up -d
          sudo docker ps
