name: Docker Automation
on: workflow_dispatch

jobs:
  build:
    runs-on: Self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker hub login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
          
      - name: Docker build & push
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nodejs-app:${{ env.SHORT_SHA }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nodejs-app:${{ env.SHORT_SHA }}
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Compose up
        run: |
          docker compose up -d
          docker ps
      
